### ISSUE TITLE
(Optional) dynamic rotation of cube

### ISSUE THREAD

**Issue by savysok** [savysok/diploma#2]
[cube_rotation.py](https://github.com/savysok/diploma/blob/master/scripts/cube_rotation.py)

create a function that rotates the cube at the beginning of the program either by 
1) random values that change over time or 
2) depending at the position of the cursor on screen (closer to the cube = slower rotation etc).

this is not really necessary, it's just for fun.

**Comment by bradleydworak** [comment]
I will investigate and work on the code to randomise the coordinates of the rotate_cube function.

**Comment by savysok** [comment]
Thnx for the help Brad. ;)
